# as_abc.s - Assembly submodule with a function
# generated by DeepSeek
.section .text

# Function: add_numbers
# Parameters: rdi = a, rsi = b
# Returns: rax = a + b
.globl add_numbers
add_numbers:
    mov %rdi, %rax      # Move first argument to rax
    add %rsi, %rax      # Add second argument
    ret                 # Return result in rax

# Function: multiply_numbers  
# Parameters: rdi = a, rsi = b
# Returns: rax = a * b
.globl multiply_numbers
multiply_numbers:
    mov %rdi, %rax      # Move first argument to rax
    imul %rsi, %rax     # Multiply by second argument
    ret                 # Return result in rax

# Function: hello_message
# Returns: rax = pointer to string
.globl hello_message
hello_message:
    lea message(%rip), %rax  # Load address of message
    ret

.section .data
message: .asciz "Hello from as_abc.s module!\n"
