# as_def.s - Assembly submodule with utility functions
# generated by DeepSeek
.section .text

# Function: subtract_numbers
# Parameters: rdi = a, rsi = b  
# Returns: rax = a - b
.globl subtract_numbers
subtract_numbers:
    mov %rdi, %rax      # Move first argument to rax
    sub %rsi, %rax      # Subtract second argument
    ret

# Function: is_even
# Parameters: rdi = number
# Returns: rax = 1 if even, 0 if odd
.globl is_even
is_even:
    mov %rdi, %rax      # Copy number to rax
    and $1, %rax        # Check least significant bit
    xor $1, %rax        # Invert: 0 becomes 1, 1 becomes 0
    ret

# Function: get_version
# Returns: rax = version number
.globl get_version
get_version:
    mov $42, %rax       # Return a constant version
    ret

.section .data
version_msg: .asciz "as_def.s module version 1.0\n"
