# as_main.s - Main program that calls library functions
# generated by DeepSeek
.section .data
    result_msg: .asciz "Result: %d\n"
    even_msg: .asciz "The number is even\n"
    odd_msg: .asciz "The number is odd\n"
    newline: .asciz "\n"

.section .text
.globl _start

_start:
    # Call add_numbers from abc.s (10 + 20)
    mov $10, %rdi
    mov $20, %rsi
    call add_numbers
    # rax now contains 30
    
    # Call multiply_numbers from abc.s (result * 2)
    mov %rax, %rdi      # Use previous result
    mov $2, %rsi
    call multiply_numbers
    # rax now contains 60
    
    # Call subtract_numbers from def.s (result - 15)
    mov %rax, %rdi
    mov $15, %rsi
    call subtract_numbers
    # rax now contains 45
    
    # Exit with the final result as status code
    mov %rax, %rdi      # store early result as exit status
    mov $60, %rax       # sys_exit
    syscall
